### ISSUE TITLE
.ignorelist comprise composer.lock

### ISSUE THREAD

**Issue by mrfroasty** [orocommerce/orocommerce#24]
Hello,

I am not so sure if the ORO core team meant this or not, but what I found out is that composer.lock is listed in the ignorelist.The composer.lock also included in GIT.

Expected results:

- Not listed in the ignore list

**Comment by aivus** [comment]
Hello, @mrfroasty.

`composer.lock` in `.gitignore` for packages (libraries) is a common approach.
See https://github.com/symfony/symfony/blob/fb65bd61d6b0fc75098ee6e3c65ded0a077aa455/.gitignore#L2

Packages (libraries) shouldn't have composer.lock files because they are shouldn't be distributed/used/installed separately.

See https://ilikekillnerds.com/2014/09/should-you-commit-composer-lock-into-your-git-repository/

**Comment by mrfroasty** [comment]
@aivus 
https://github.com/symfony/symfony/blob/fb65bd61d6b0fc75098ee6e3c65ded0a077aa455/.gitignore#L2

That seems to be correct, its in ignorelist and not forced into GIT.But the issue is that it has been ignored, but on the backdoor forced into GIT.

**Comment by aivus** [comment]
@mrfroasty what repository do you mean?
I don't see `composer.lock` in this repo.

**Comment by mrfroasty** [comment]
@aivus 
I am not so sure as it seems like its gone, but definately it has been there {see commit below}

```
commit 0da0e314f91234bf24b992b6bb599b98a5850fb9
Author: Andrey Yatsenco <yatsenco@gmail.com>
Date:   Tue Jan 17 20:44:15 2017 +0200
```

Many thanks as it seems resolved, the lock is gone

**Comment by aivus** [comment]
@mrfroasty seems you are talking about another repo:
https://github.com/orocommerce/orocommerce-application/

`composer.lock` in application repo is ok
